server:
  port: 8888
spring:
  application:
    name: gateway-service-zuul

#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
zuul:
  routes:
#    baidu:
#      path: /wy/**
#      url: http://localhost:8910/hello
    api-a.path: /provider/**
    api-a.serviceId: eureka-service-provider
# 注册服务
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8000/eureka/