# 配置服务器端口
server:
  port: 8921
spring:
  application:
    name: eureka-consumer-feign
# 注册服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
# 配置启动断路器
feign:
  hystrix:
    enabled: true